#!/bin/sh

# drh 2016-08-18
# I have manually extracted these files myself and added them to the git
# repository  so that they can be modified and tracked in version control.
# Hence, this script doesn't need to do anything anymore.

# Get the original cernlib sources

#tar -zxvf $CERN/cernlib_2005.tgz > cernlib_2005_orig.lst

# Unpack the source files and set up the build structure in $CERN

#list=`ls src_*.gz`

#for ffile in $list
#do
#  gunzip -c $ffile | tar xf -
#done

# Overload corrections to cernlib 2005

#tar -zxvf $CERN/cernlib.2005.corr.tgz > cernlib_corr.lst

