#!/bin/sh

# Get the original cernlib sources

tar -zxvf $CERN/cernlib_2005.tgz > cernlib_2005_orig.lst

# Unpack the source files and set up the build structure in $CERN

list=`ls src_*.gz`

for ffile in $list
do
  gunzip -c $ffile | tar xf -
done

# Overload corrections to cernlib 2005

tar -zxvf $CERN/cernlib.2005.corr.tgz > cernlib_corr.lst

