#!/bin/sh

# Get the original cernlib sources and the additional lapack (blas) sources

gtar -zxvf $CERN/cernlib_2005.tgz > cernlib_2005_orig.lst

# Unpack the source files and set up the build structure in $CERN

list=`ls src_*.gz`

for ffile in $list
do
  gunzip -c $ffile | tar xf -
done

# Overload my corrections to cernlib 2005

gtar -zxvf $CERN/cernlib.2005.corr.tgz > cernlib_corr.lst

